# Generated by Django 4.1.7 on 2023-03-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazon',
            name='ordered_items',
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='orders',
        ),
    ]
